import {
  faSpinner,
  faStopwatch,
  faCheck,
  faGripLines,
  faSync,
  faArchive,
  faPen,
  faClone,
  faEllipsisH,
  faLongArrowAltLeft,
  faPlus,
  faPlayCircle,
  faPauseCircle,
  faStopCircle,
  faPause,
  faTimes,
  faChartArea,
  faTasks,
  faChartLine,
  faSortDown,
  faCog,
  faArrowLeft,
  faUndo,
  faTrashAlt,
  faEyeSlash,
  faBold,
  faItalic,
  faStrikethrough,
  faUnderline,
  faCode,
  faParagraph,
  faHeading,
  faListUl,
  faListOl,
  faQuoteRight,
  faMinus,
  faUndoAlt,
  faRedoAlt,
  faSignOutAlt,
} from '@fortawesome/free-solid-svg-icons';

export default {
  archive: faArchive.icon[4],
  'arrow-left': faArrowLeft.icon[4],
  bold: faBold.icon[4],
  'chart-area': faChartArea.icon[4],
  'chart-line': faChartLine.icon[4],
  check: faCheck.icon[4],
  clone: faClone.icon[4],
  code: faCode.icon[4],
  cog: faCog.icon[4],
  'ellipsis-h': faEllipsisH.icon[4],
  'eye-slash': faEyeSlash.icon[4],
  'grip-lines': faGripLines.icon[4],
  heading: faHeading.icon[4],
  italic: faItalic.icon[4],
  'list-ol': faListOl.icon[4],
  'list-ul': faListUl.icon[4],
  'long-arrow-alt-left': faLongArrowAltLeft.icon[4],
  minus: faMinus.icon[4],
  paragraph: faParagraph.icon[4],
  pause: faPause.icon[4],
  'pause-circle': faPauseCircle.icon[4],
  pen: faPen.icon[4],
  'play-circle': faPlayCircle.icon[4],
  plus: faPlus.icon[4],
  'quote-right': faQuoteRight.icon[4],
  'redo-alt': faRedoAlt.icon[4],
  'sign-out-alt': faSignOutAlt.icon[4],
  'sort-down': faSortDown.icon[4],
  spinner: faSpinner.icon[4],
  'stop-circle': faStopCircle.icon[4],
  stopwatch: faStopwatch.icon[4],
  strikethrough: faStrikethrough.icon[4],
  sync: faSync.icon[4],
  tasks: faTasks.icon[4],
  times: faTimes.icon[4],
  'trash-alt': faTrashAlt.icon[4],
  underline: faUnderline.icon[4],
  undo: faUndo.icon[4],
  'undo-alt': faUndoAlt.icon[4],
};
